INSERT INTO cars (car_id, availability_status, category, color, created_at, manufacturer, model, number_of_doors, number_of_seats, price_per_day, transmission_type, updated_at, year) VALUES
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Gray', NOW(), 'Honda', 'Accord', 4, 5, 95.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Black', NOW(), 'Honda', 'Accord', 4, 5, 95.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'White', NOW(), 'Honda', 'Accord', 4, 5, 95.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Silver', NOW(), 'Nissan', 'Altima', 4, 5, 92.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Black', NOW(), 'Nissan', 'Altima', 4, 5, 92.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'White', NOW(), 'Nissan', 'Altima', 4, 5, 92.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'White', NOW(), 'Hyundai', 'Sonata', 4, 5, 90.00, 'Automatic', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Blue', NOW(), 'Hyundai', 'Sonata', 4, 5, 90.00, 'Automatic', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Silver', NOW(), 'Hyundai', 'Sonata', 4, 5, 90.00, 'Automatic', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Black', NOW(), 'Kia', 'K5', 4, 5, 100.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Red', NOW(), 'Kia', 'K5', 4, 5, 100.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'White', NOW(), 'Kia', 'K5', 4, 5, 100.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Red', NOW(), 'Mazda', 'Mazda6', 4, 5, 98.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Black', NOW(), 'Mazda', 'Mazda6', 4, 5, 98.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'White', NOW(), 'Mazda', 'Mazda6', 4, 5, 98.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Blue', NOW(), 'Chevrolet', 'Malibu', 4, 5, 97.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Black', NOW(), 'Chevrolet', 'Malibu', 4, 5, 97.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'White', NOW(), 'Chevrolet', 'Malibu', 4, 5, 97.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'White', NOW(), 'Tesla', 'Model 3', 4, 5, 110.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Black', NOW(), 'Tesla', 'Model 3', 4, 5, 110.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Red', NOW(), 'Tesla', 'Model 3', 4, 5, 110.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Black', NOW(), 'BMW', '3 Series', 4, 5, 120.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'White', NOW(), 'BMW', '3 Series', 4, 5, 120.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SEDAN', 'Gray', NOW(), 'BMW', '3 Series', 4, 5, 120.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'Red', NOW(), 'Porsche', '911 Carrera', 2, 2, 200.00, 'Manual', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'Black', NOW(), 'Porsche', '911 Carrera', 2, 2, 200.00, 'Manual', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'White', NOW(), 'Porsche', '911 Carrera', 2, 2, 200.00, 'Manual', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'Yellow', NOW(), 'Ferrari', 'F8 Tributo', 2, 2, 250.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'Red', NOW(), 'Ferrari', 'F8 Tributo', 2, 2, 250.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'Black', NOW(), 'Ferrari', 'F8 Tributo', 2, 2, 250.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'Blue', NOW(), 'BMW', 'M4 Competition', 2, 2, 150.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'Black', NOW(), 'BMW', 'M4 Competition', 2, 2, 150.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'White', NOW(), 'BMW', 'M4 Competition', 2, 2, 150.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'Orange', NOW(), 'Chevrolet', 'Corvette', 2, 2, 140.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'Black', NOW(), 'Chevrolet', 'Corvette', 2, 2, 140.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SPORT', 'White', NOW(), 'Chevrolet', 'Corvette', 2, 2, 140.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'White', NOW(), 'Chevrolet', 'Suburban', 5, 8, 130.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'Black', NOW(), 'Chevrolet', 'Suburban', 5, 8, 130.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'Gray', NOW(), 'Chevrolet', 'Suburban', 5, 8, 130.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'Silver', NOW(), 'Toyota', 'Highlander', 5, 7, 125.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'Blue', NOW(), 'Toyota', 'Highlander', 5, 7, 125.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'White', NOW(), 'Toyota', 'Highlander', 5, 7, 125.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'Black', NOW(), 'Ford', 'Explorer', 5, 7, 135.00, 'Automatic', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'Red', NOW(), 'Ford', 'Explorer', 5, 7, 135.00, 'Automatic', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'Silver', NOW(), 'Ford', 'Explorer', 5, 7, 135.00, 'Automatic', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'Green', NOW(), 'Jeep', 'Grand Cherokee', 5, 5, 140.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'Black', NOW(), 'Jeep', 'Grand Cherokee', 5, 5, 140.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'SUV', 'White', NOW(), 'Jeep', 'Grand Cherokee', 5, 5, 140.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'Silver', NOW(), 'Honda', 'Odyssey', 5, 6, 115.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'White', NOW(), 'Honda', 'Odyssey', 5, 6, 115.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'Black', NOW(), 'Honda', 'Odyssey', 5, 6, 115.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'White', NOW(), 'Toyota', 'Sienna', 5, 7, 120.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'Silver', NOW(), 'Toyota', 'Sienna', 5, 7, 120.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'Gray', NOW(), 'Toyota', 'Sienna', 5, 7, 120.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'Blue', NOW(), 'Chrysler', 'Pacifica', 5, 7, 118.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'White', NOW(), 'Chrysler', 'Pacifica', 5, 7, 118.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'Black', NOW(), 'Chrysler', 'Pacifica', 5, 7, 118.00, 'Automatic', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'Red', NOW(), 'Citroën', 'C4 Picasso', 5, 5, 105.00, 'Automatic', NOW(), 2019),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'Blue', NOW(), 'Citroën', 'C4 Picasso', 5, 5, 105.00, 'Automatic', NOW(), 2019),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'MPV', 'Gray', NOW(), 'Citroën', 'C4 Picasso', 5, 5, 105.00, 'Automatic', NOW(), 2019),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'Blue', NOW(), 'Ford', 'Mustang', 2, 4, 150.00, 'Manual', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'Red', NOW(), 'Ford', 'Mustang', 2, 4, 150.00, 'Manual', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'Black', NOW(), 'Ford', 'Mustang', 2, 4, 150.00, 'Manual', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'Gray', NOW(), 'Audi', 'A5', 2, 4, 145.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'Black', NOW(), 'Audi', 'A5', 2, 4, 145.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'White', NOW(), 'Audi', 'A5', 2, 4, 145.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'Black', NOW(), 'BMW', '4 Series', 2, 4, 155.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'White', NOW(), 'BMW', '4 Series', 2, 4, 155.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'Gray', NOW(), 'BMW', '4 Series', 2, 4, 155.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'Red', NOW(), 'Audi', 'TT', 2, 4, 135.00, 'Manual', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'Black', NOW(), 'Audi', 'TT', 2, 4, 135.00, 'Manual', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'COUPE', 'White', NOW(), 'Audi', 'TT', 2, 4, 135.00, 'Manual', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'Yellow', NOW(), 'Mini', 'Mini Cooper', 4, 4, 80.00, 'Manual', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'Black', NOW(), 'Mini', 'Mini Cooper', 4, 4, 80.00, 'Manual', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'White', NOW(), 'Mini', 'Mini Cooper', 4, 4, 80.00, 'Manual', NOW(), 2023),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'White', NOW(), 'Volkswagen', 'Golf', 4, 5, 85.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'Blue', NOW(), 'Volkswagen', 'Golf', 4, 5, 85.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'Gray', NOW(), 'Volkswagen', 'Golf', 4, 5, 85.00, 'Automatic', NOW(), 2021),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'Blue', NOW(), 'Ford', 'Focus', 4, 5, 75.00, 'Manual', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'Black', NOW(), 'Ford', 'Focus', 4, 5, 75.00, 'Manual', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'White', NOW(), 'Ford', 'Focus', 4, 5, 75.00, 'Manual', NOW(), 2020),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'Silver', NOW(), 'Honda', 'Civic Hatch', 4, 5, 88.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'Gray', NOW(), 'Honda', 'Civic Hatch', 4, 5, 88.00, 'Automatic', NOW(), 2022),
(UUID_TO_BIN(UUID()), 'AVAILABLE', 'HATCHBACK', 'White', NOW(), 'Honda', 'Civic Hatch', 4, 5, 88.00, 'Automatic', NOW(), 2022);
